services:
  - type: web
    name: atlas-backend
    runtime: python
    plan: free
    pythonVersion: "3.11.0"
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: JSEARCH_API_KEY
        sync: false
      - key: APP_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./data/atlas.db
      - key: CHROMA_PATH
        value: ./data/chroma
      - key: FRONTEND_URL
        sync: false


  - type: web
    name: atlas-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
